### PR TITLE
docs: confluence document migration

### PR DESCRIPTION
**Pull request by curlyreeve**

### CODE REVIEW

**Review by Sandy-at-Tazama — DISMISSED** [review]

**Review by Justus-at-Tazama — APPROVED** [review]
- Updated base branch
 - Updated commit message
 - Integrated readme.md.old content into readme.md
 - Deleted readme.me.old

**Review by Sandy-at-Tazama — APPROVED** [review]
## 1.  Unable to access Lextego confluence links
image

**Comment by curlyreeve** [comment]
> ## 1. Unable to access Lextego confluence links
> image

These are the original links on the confluence to the jira tickets. The only option is to delete the links. How would you like me to proceed?

https://frmscoe.atlassian.net/wiki/spaces/FRMS/pages/1739897/1.+Transaction+Monitoring+Service+TMS

**Comment by Sandy-at-Tazama** [comment]
Please keep the links to confluence.  @curlyreeve

**Pull request merged**
